import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Link href="/about">About me</Link>
    
<h1>Welcome to my website</h1>
<h2>My name is Ricky Thijssen</h2>    
<p id="first-paragraph">Hondjes zijn best wel leuk, daarom deze website over hondjes.</p>         
<p className="Special-Snowflake">Mocht u ook een hond willen, lees dan gerust verder.</p>         
<p>Fun fact: honden zeggen soms woef!</p>
<p className="Special-Snowflake ultra-super-duper-special-flake">Veel plezier met deze site. Joe.</p>

<a href="https://nl.wikipedia.org/wiki/Hond">Klik hier voor honden info</a>


<h1> Een stukje poezie:</h1>

     <h2> Woef </h2>
     <h3> woef woef </h3>
     <h4> woef woef woef </h4>
     <h5> woef woef woef woef </h5>
     <p> Hondjes zijn best wel leuk</p>

     

     

    </div>
  )
}

export default Home
